baseURL = "https://johntechtalks.com/" # Must end with splash
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disqusShortname = "johntechtalks-com"

staticDir = ["static"]

theme = "Niello"

[params]
copyright = "&#xA9; 2024 by John Nguyen. All Rights Reserved."
google_ad_client = "ca-pub-******"
ga4 = "G-******"
sharethis = ""

[outputs]
home = ["HTML", "JSON"]

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Categories"
    pageRef = "/categories"
    weight = 2
  [[menus.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 3
  [[menus.main]]
    name = "Contact"
    pageRef = "/contact"
    weight = 4
