baseURL = "https://johntechtalks.com/" # Must end with splash
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disqusShortname = "johntechtalks-com"

staticDir = ["static"]

theme = "Niello"

[params]
copyright = "John Tech Talks &#xA9; 2024 by John Nguyen. | All Rights Reserved."
sharethis = "677ac2478d50b9001ab3b268"
[params.google]
	google_ad_client = "ca-pub-4662966258960893"
	ga4 = "G-V54VPQF9VK"
[params.bannershowcase]
	categories = ["recommended"]
	limit = 5
[params.email]
	contact = "j4nguyen134@gmail.com"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie", "search"]


[languages]
	[languages.en]
		title = "John Tech Talks - Discover Issues, Share Solutions."
		languageCode = "en-us"
		LanguageName = "🇺🇸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3
		[[languages.en.menus.main]]
			name = 'Contact'
			pageRef = '/contact'
			weight = 4


[outputs]
  home = ["HTML", "JSON"]